import { z } from "zod";
import { IMAGE_MIME_TYPES } from "@/lib/data/types";

/** Provider-facing / wire message shape. reasoningContent is replayed only for tool-call turns (§3.5/§9). */
export const wireMessageSchema = z.object({
  role: z.enum(["system", "user", "assistant", "tool"]),
  content: z.string(),
  reasoningContent: z.string().optional(),
  toolCallId: z.string().optional(),
  /** Marks assistant turns that performed tool calls — drives reasoning replay. */
  hadToolCall: z.boolean().optional(),
  /** Assistant tool-call payload (set server-side during the tool loop). */
  toolCalls: z
    .array(
      z.object({
        id: z.string(),
        type: z.literal("function"),
        function: z.object({ name: z.string(), arguments: z.string() }),
      })
    )
    .optional(),
});
export type WireMessage = z.infer<typeof wireMessageSchema>;

export const chatModeSchema = z.enum(["chat", "code-build", "code-discuss", "code-plan", "code-verify"]);
export type ChatModeWire = z.infer<typeof chatModeSchema>;

export const attachedImageSchema = z.object({
  base64: z.string().min(1),
  mimeType: z.enum(IMAGE_MIME_TYPES),
});
export type AttachedImageWire = z.infer<typeof attachedImageSchema>;

/** A PDF parsed to text client-side (free, ungated). */
export const attachedDocumentSchema = z.object({
  name: z.string(),
  text: z.string().min(1),
});
export type AttachedDocumentWire = z.infer<typeof attachedDocumentSchema>;

/** A scanned PDF (no text layer) rendered to page images for AI analysis. */
export const scannedPdfSchema = z.object({
  name: z.string(),
  pages: z.array(attachedImageSchema).min(1),
});
export type ScannedPdfWire = z.infer<typeof scannedPdfSchema>;

/** §18 — chat route request contract. */
export const chatRequestSchema = z.object({
  messages: z.array(wireMessageSchema).min(1),
  forgeModelId: z.enum(["spark-2.5", "magnum-2.8"]),
  effort: z.enum(["low", "medium", "high", "xhigh", "max"]),
  thinking: z.boolean(),
  mode: chatModeSchema.default("chat"),
  conversationId: z.string().optional(),
  conversationTitle: z.string().optional(),
  projectId: z.string().optional(),
  toolsEnabled: z.boolean().optional(),
  /** Whether the web_search tool may be offered this turn (toggle, default on). */
  webSearch: z.boolean().optional(),
  /** Optional images to analyze server-side before sending text-only context. */
  attachedImages: z.array(attachedImageSchema).optional(),
  /** PDFs parsed to text in the browser (free, ungated context). */
  documents: z.array(attachedDocumentSchema).optional(),
  /** Scanned PDFs rendered to page images for gated AI analysis. */
  scannedPdfs: z.array(scannedPdfSchema).optional(),
  connectorIds: z.array(z.string()).optional(),
  agentId: z.string().optional(),
  skillSlugs: z.array(z.string()).optional(),
  /** Resolved active skills (name + instructions) injected into the prompt. */
  skills: z
    .array(z.object({ name: z.string(), instructions: z.string() }))
    .optional(),
  /** All of the user's skills (name + slug + description) — for editing by slug. */
  skillCatalog: z
    .array(
      z.object({
        name: z.string(),
        slug: z.string(),
        description: z.string().optional(),
      })
    )
    .optional(),
  incognito: z.boolean().optional(),
  /** Forge Code: the project's file tree + contents, injected as context. */
  projectContext: z.string().optional(),
  /** Legacy flag ignored by /api/chat. Titles are generated by /api/title. */
  wantTitle: z.boolean().optional(),
});
export type ChatRequest = z.infer<typeof chatRequestSchema>;

/** Events streamed to the browser as NDJSON. Contains NO provider identifiers. */
export type StreamEventWire =
  | { t: "reasoning"; d: string }
  | { t: "content"; d: string }
  | {
      t: "status";
      d: string;
      done?: boolean;
      id?: string;
      n?: number;
      sources?: { title: string; url: string }[];
    }
  | {
      t: "image";
      id: string;
      loadingText?: string;
      done?: boolean;
      imageUrl?: string;
      prompt?: string;
      error?: string;
      notice?: string;
    }
  | { t: "title"; d: string }
  | {
      t: "done";
      finish: string;
      tokens: number;
      /** Token-usage breakdown for the completed turn (usage tracking, §15). */
      realTokens?: number;
      forgeTokens?: number;
      multiplier?: number;
    }
  | { t: "error"; d: string };

export function encodeEvent(e: StreamEventWire): string {
  return JSON.stringify(e) + "\n";
}
